"""Reference baselines for Dunhuang Pairwise Benchmark v0.1.

The package initializer is dependency-light.  Public attributes retain their
historical identities through PEP 562 lazy resolution, so importing a
metadata-only submodule does not eagerly import torch or image/model helpers.
"""

from __future__ import annotations

from importlib import import_module
from typing import Dict, Tuple


_LAZY_EXPORTS: Dict[str, Tuple[str, str]] = {
    "ALIGNMENT_POSE_BRIDGE_VERSION": (".b3_alignment_pose", "ALIGNMENT_POSE_BRIDGE_VERSION"),
    "AdaptedPatchFeatures": (".b2_feature_adapter", "AdaptedPatchFeatures"),
    "AlignmentEvidenceProvenance": (".b3_alignment_pose", "AlignmentEvidenceProvenance"),
    "AlignmentMode": (".b1_edge_scorer", "AlignmentMode"),
    "AlignmentParameterSource": (".b2_ordered_alignment", "AlignmentParameterSource"),
    "AlignmentPoseBridgeResult": (".b3_alignment_pose", "AlignmentPoseBridgeResult"),
    "AlignmentPoseBridgeStatus": (".b3_alignment_pose", "AlignmentPoseBridgeStatus"),
    "AlignmentStatus": (".b2_ordered_alignment", "AlignmentStatus"),
    "ArchiveImageError": (".archive_image_loader", "ArchiveImageError"),
    "ArchiveImageLoader": (".archive_image_loader", "ArchiveImageLoader"),
    "ArchiveImageLoaderConfig": (".archive_image_loader", "ArchiveImageLoaderConfig"),
    "ArchiveImageLoaderStats": (".archive_image_loader", "ArchiveImageLoaderStats"),
    "ArchiveImageRef": (".real_pair_stream", "ArchiveImageRef"),
    "AttributeRecordAdapter": (".b0_siamese", "AttributeRecordAdapter"),
    "B0SiameseConfig": (".b0_siamese", "B0SiameseConfig"),
    "B0SiameseEvaluator": (".b0_siamese", "B0SiameseEvaluator"),
    "B1EdgeScorerConfig": (".b1_edge_scorer", "B1EdgeScorerConfig"),
    "B1PairScore": (".b1_edge_scorer", "B1PairScore"),
    "B1_EDGE_SCORER_VERSION": (".b1_edge_scorer", "B1_EDGE_SCORER_VERSION"),
    "BootstrapConfig": (".b0_siamese", "BootstrapConfig"),
    "BootstrapUnit": (".b0_siamese", "BootstrapUnit"),
    "BoundaryReference": (".b1_edge_scorer", "BoundaryReference"),
    "BoundarySaddlePolicy": (".b1_contours", "BoundarySaddlePolicy"),
    "CONTOUR_VERSION": (".b1_contours", "CONTOUR_VERSION"),
    "COORDINATE_ORDER": (".b1_contours", "COORDINATE_ORDER"),
    "CanonicalContour": (".b1_contours", "CanonicalContour"),
    "CardinalSide": (".b1_contours", "CardinalSide"),
    "CardinalSideRunsResult": (".b1_contours", "CardinalSideRunsResult"),
    "ContourOnlyPreprocessResult": (".b1_contours", "ContourOnlyPreprocessResult"),
    "ContourPatch": (".b2_patch_sampler", "ContourPatch"),
    "ContourPreprocessConfig": (".b1_contours", "ContourPreprocessConfig"),
    "ContourPreprocessResult": (".b1_contours", "ContourPreprocessResult"),
    "ContourQuality": (".b1_contours", "ContourQuality"),
    "ContourSide": (".b1_contours", "ContourSide"),
    "ContourStatus": (".b1_contours", "ContourStatus"),
    "CoordinateFrameProvenance": (".b3_alignment_pose", "CoordinateFrameProvenance"),
    "DirectionScore": (".b1_edge_scorer", "DirectionScore"),
    "DirectionStrategy": (".b0_siamese", "DirectionStrategy"),
    "ECCVSplitExposureAudit": (".real_pair_stream", "ECCVSplitExposureAudit"),
    "ECCVSplitExposureEvidence": (".real_pair_stream", "ECCVSplitExposureEvidence"),
    "ECCV_STREAM_EXPOSURE_SCHEMA_VERSION": (".real_pair_stream", "ECCV_STREAM_EXPOSURE_SCHEMA_VERSION"),
    "EdgeOrientation": (".b1_sequence_metrics", "EdgeOrientation"),
    "EdgeScorerStatus": (".b1_edge_scorer", "EdgeScorerStatus"),
    "EvaluationReport": (".b0_siamese", "EvaluationReport"),
    "ExcludedProfileError": (".real_pair_stream", "ExcludedProfileError"),
    "FeatureSequence": (".b2_ordered_alignment", "FeatureSequence"),
    "ForegroundPolarity": (".b1_contours", "ForegroundPolarity"),
    "IMAGE_LOADER_VERSION": (".archive_image_loader", "IMAGE_LOADER_VERSION"),
    "LocalCorrespondence": (".b2_ordered_alignment", "LocalCorrespondence"),
    "MacroMetricSummary": (".b0_siamese", "MacroMetricSummary"),
    "MappedPatchCorrespondence": (".b3_alignment_pose", "MappedPatchCorrespondence"),
    "MaskEncoding": (".b2_feature_adapter", "MaskEncoding"),
    "MetricValidity": (".b1_sequence_metrics", "MetricValidity"),
    "ModelOutputMode": (".b0_siamese", "ModelOutputMode"),
    "ORDERED_ALIGNMENT_VERSION": (".b2_ordered_alignment", "ORDERED_ALIGNMENT_VERSION"),
    "ORIENTATION_HYPOTHESES_VERSION": (".b3_orientation_hypotheses", "ORIENTATION_HYPOTHESES_VERSION"),
    "OrderedAlignmentConfig": (".b2_ordered_alignment", "OrderedAlignmentConfig"),
    "OrderedAlignmentResult": (".b2_ordered_alignment", "OrderedAlignmentResult"),
    "OrientationComparison": (".b1_sequence_metrics", "OrientationComparison"),
    "OrientationComparisonResult": (".b2_ordered_alignment", "OrientationComparisonResult"),
    "OrientationPoseHypothesesResult": (".b3_orientation_hypotheses", "OrientationPoseHypothesesResult"),
    "PATCH_FEATURE_ADAPTER_VERSION": (".b2_feature_adapter", "PATCH_FEATURE_ADAPTER_VERSION"),
    "PATCH_SAMPLER_VERSION": (".b2_patch_sampler", "PATCH_SAMPLER_VERSION"),
    "POSE_RANSAC_VERSION": (".b3_pose_ransac", "POSE_RANSAC_VERSION"),
    "PairStreamError": (".real_pair_stream", "PairStreamError"),
    "ParameterSource": (".b1_edge_scorer", "ParameterSource"),
    "PatchFeatureConfig": (".b2_feature_adapter", "PatchFeatureConfig"),
    "PatchFeatureError": (".b2_feature_adapter", "PatchFeatureError"),
    "PatchFeatureMode": (".b2_feature_adapter", "PatchFeatureMode"),
    "PatchMetadata": (".b2_patch_sampler", "PatchMetadata"),
    "PatchSamplerConfig": (".b2_patch_sampler", "PatchSamplerConfig"),
    "PatchSamplingQuality": (".b2_patch_sampler", "PatchSamplingQuality"),
    "PatchSamplingResult": (".b2_patch_sampler", "PatchSamplingResult"),
    "PatchSamplingStatus": (".b2_patch_sampler", "PatchSamplingStatus"),
    "PoseEstimationStatus": (".b3_pose_ransac", "PoseEstimationStatus"),
    "PoseParameterProvenance": (".b3_pose_ransac", "PoseParameterProvenance"),
    "PoseParameterSource": (".b3_pose_ransac", "PoseParameterSource"),
    "PoseRansacConfig": (".b3_pose_ransac", "PoseRansacConfig"),
    "RealPairRecord": (".real_pair_stream", "RealPairRecord"),
    "ResampledPath": (".b1_contours", "ResampledPath"),
    "RigidPoseEstimate": (".b3_pose_ransac", "RigidPoseEstimate"),
    "SEQUENCE_METRICS_VERSION": (".b1_sequence_metrics", "SEQUENCE_METRICS_VERSION"),
    "SIDE_RUNS_VERSION": (".b1_contours", "SIDE_RUNS_VERSION"),
    "STREAM_SCHEMA_VERSION": (".real_pair_stream", "STREAM_SCHEMA_VERSION"),
    "SequenceMetric": (".b1_sequence_metrics", "SequenceMetric"),
    "SequenceMetricResult": (".b1_sequence_metrics", "SequenceMetricResult"),
    "SideRunExtractionQuality": (".b1_contours", "SideRunExtractionQuality"),
    "SideRunExtractionStatus": (".b1_contours", "SideRunExtractionStatus"),
    "SideSearchMode": (".b1_edge_scorer", "SideSearchMode"),
    "SplitManifestError": (".real_pair_stream", "SplitManifestError"),
    "SplitManifestView": (".real_pair_stream", "SplitManifestView"),
    "TextureEncoding": (".b2_feature_adapter", "TextureEncoding"),
    "ThresholdArtifact": (".b0_siamese", "ThresholdArtifact"),
    "ThresholdObjective": (".b0_siamese", "ThresholdObjective"),
    "TraversalOrientation": (".b2_ordered_alignment", "TraversalOrientation"),
    "adapt_patch_features": (".b2_feature_adapter", "adapt_patch_features"),
    "arc_length_resample": (".b1_contours", "arc_length_resample"),
    "compare_edge_orientations": (".b1_sequence_metrics", "compare_edge_orientations"),
    "compare_ordered_feature_sequences": (".b2_ordered_alignment", "compare_ordered_feature_sequences"),
    "cosine_similarity_matrix": (".b2_ordered_alignment", "cosine_similarity_matrix"),
    "discrete_frechet_distance": (".b1_sequence_metrics", "discrete_frechet_distance"),
    "dtw_distance": (".b1_sequence_metrics", "dtw_distance"),
    "estimate_orientation_pose_hypotheses": (".b3_orientation_hypotheses", "estimate_orientation_pose_hypotheses"),
    "estimate_pose_from_ordered_alignment": (".b3_alignment_pose", "estimate_pose_from_ordered_alignment"),
    "estimate_rigid_pose_ransac": (".b3_pose_ransac", "estimate_rigid_pose_ransac"),
    "extract_cardinal_side_runs": (".b1_contours", "extract_cardinal_side_runs"),
    "iter_eccv_pair_records": (".real_pair_stream", "iter_eccv_pair_records"),
    "iter_mm_pair_records": (".real_pair_stream", "iter_mm_pair_records"),
    "iter_real_pair_records": (".real_pair_stream", "iter_real_pair_records"),
    "lcss_similarity": (".b1_sequence_metrics", "lcss_similarity"),
    "load_split_manifest": (".real_pair_stream", "load_split_manifest"),
    "preprocess_mask": (".b1_contours", "preprocess_mask"),
    "preprocess_mask_contour_only": (".b1_contours", "preprocess_mask_contour_only"),
    "sample_side_patches": (".b2_patch_sampler", "sample_side_patches"),
    "score_cardinal_edges": (".b1_edge_scorer", "score_cardinal_edges"),
    "transform_points_row_col": (".b3_pose_ransac", "transform_points_row_col"),
}


def __getattr__(name: str):
    try:
        module_name, attribute_name = _LAZY_EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(
            "module {!r} has no attribute {!r}".format(__name__, name)
        ) from exc
    value = getattr(import_module(module_name, __name__), attribute_name)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(_LAZY_EXPORTS))


__all__ = [
    "AdaptedPatchFeatures",
    "ALIGNMENT_POSE_BRIDGE_VERSION",
    "AlignmentEvidenceProvenance",
    "AlignmentMode",
    "AlignmentParameterSource",
    "AlignmentStatus",
    "AlignmentPoseBridgeResult",
    "AlignmentPoseBridgeStatus",
    "AttributeRecordAdapter",
    "ArchiveImageError",
    "ArchiveImageLoader",
    "ArchiveImageLoaderConfig",
    "ArchiveImageLoaderStats",
    "ArchiveImageRef",
    "ECCVSplitExposureAudit",
    "ECCVSplitExposureEvidence",
    "ECCV_STREAM_EXPOSURE_SCHEMA_VERSION",
    "B1_EDGE_SCORER_VERSION",
    "B0SiameseConfig",
    "B0SiameseEvaluator",
    "B1EdgeScorerConfig",
    "B1PairScore",
    "BoundaryReference",
    "BootstrapConfig",
    "BootstrapUnit",
    "CONTOUR_VERSION",
    "COORDINATE_ORDER",
    "SIDE_RUNS_VERSION",
    "BoundarySaddlePolicy",
    "CardinalSideRunsResult",
    "CanonicalContour",
    "CardinalSide",
    "ContourPreprocessConfig",
    "ContourPreprocessResult",
    "ContourOnlyPreprocessResult",
    "ContourPatch",
    "ContourQuality",
    "ContourSide",
    "ContourStatus",
    "CoordinateFrameProvenance",
    "DirectionScore",
    "DirectionStrategy",
    "EdgeOrientation",
    "EdgeScorerStatus",
    "EvaluationReport",
    "ExcludedProfileError",
    "ForegroundPolarity",
    "FeatureSequence",
    "IMAGE_LOADER_VERSION",
    "LocalCorrespondence",
    "MacroMetricSummary",
    "MappedPatchCorrespondence",
    "MaskEncoding",
    "MetricValidity",
    "ModelOutputMode",
    "ORDERED_ALIGNMENT_VERSION",
    "ORIENTATION_HYPOTHESES_VERSION",
    "OrderedAlignmentConfig",
    "OrderedAlignmentResult",
    "OrientationComparison",
    "OrientationComparisonResult",
    "OrientationPoseHypothesesResult",
    "PATCH_SAMPLER_VERSION",
    "PATCH_FEATURE_ADAPTER_VERSION",
    "POSE_RANSAC_VERSION",
    "PairStreamError",
    "PatchMetadata",
    "PatchFeatureConfig",
    "PatchFeatureError",
    "PatchFeatureMode",
    "PatchSamplerConfig",
    "PatchSamplingQuality",
    "PatchSamplingResult",
    "PatchSamplingStatus",
    "ParameterSource",
    "PoseEstimationStatus",
    "PoseParameterProvenance",
    "PoseParameterSource",
    "PoseRansacConfig",
    "RealPairRecord",
    "ResampledPath",
    "RigidPoseEstimate",
    "SEQUENCE_METRICS_VERSION",
    "STREAM_SCHEMA_VERSION",
    "SequenceMetric",
    "SequenceMetricResult",
    "SideSearchMode",
    "SideRunExtractionQuality",
    "SideRunExtractionStatus",
    "SplitManifestError",
    "SplitManifestView",
    "ThresholdArtifact",
    "ThresholdObjective",
    "TextureEncoding",
    "TraversalOrientation",
    "arc_length_resample",
    "adapt_patch_features",
    "compare_edge_orientations",
    "compare_ordered_feature_sequences",
    "cosine_similarity_matrix",
    "discrete_frechet_distance",
    "dtw_distance",
    "estimate_rigid_pose_ransac",
    "estimate_pose_from_ordered_alignment",
    "estimate_orientation_pose_hypotheses",
    "extract_cardinal_side_runs",
    "iter_eccv_pair_records",
    "iter_mm_pair_records",
    "iter_real_pair_records",
    "lcss_similarity",
    "load_split_manifest",
    "preprocess_mask",
    "preprocess_mask_contour_only",
    "sample_side_patches",
    "score_cardinal_edges",
    "transform_points_row_col",
]

